export const ADD_SERVICES = 'SERVICES::ADD_SERVICES';
export const CLEAR_SERVICES = 'SERVICES::CLEAR_SERVICES';
export const DELETE_SERVICES = 'SERVICES::DELETE_SERVICES';

export default {
  ADD_SERVICES,
  CLEAR_SERVICES,
  DELETE_SERVICES
}