export const ADD_ALL_SERVICES = 'SERVICES::ADD_ALL_SERVICES';
export const ADD_ONE_SERVICE = 'SERVICES::ADD_ONE_SERVICE';
export const CLEAR_SERVICES = 'SERVICES::CLEAR_SERVICES';
export const DELETE_SERVICE = 'SERVICES::DELETE_SERVICE';