export const ADD_MASTERS = 'MASTER::ADD_MASTERS';
export const CLEAR_MASTERS = 'MASTER::CLEAR_MASTERS';
export const DELETE_MASTER = 'MASTER::DELETE_MASTER';

export default {
  ADD_MASTERS,
  CLEAR_MASTERS,
  DELETE_MASTER
}