export const ADD_MASTER = 'MASTER::ADD_MASTERS';
export const CLEAR_MASTER = 'MASTER::CLEAR_MASTER';
export const DELETE_MASTER = 'MASTER::DELETE_MASTER';

export default {
    ADD_MASTER,
    CLEAR_MASTER,
    DELETE_MASTER
}